### ISSUE TITLE
How drawing gradient color

### ISSUE THREAD

**Issue by RickMenza** [azure-rtos/guix#21]
Hi,
I want to draw a slider using gradient color (black to a color returning by the application).
Since I don't know which color will be used by the application, I need to creat it at runtime.

I think I should use the gx_utility_gradient_create function but I don't know how to use it and draw a pixelmap containing my gradient color.

Is someone has a code snippet exemple to help me how to do?
Thanks in advance!
Richard

**Comment by jdeere5220** [comment]
Hello @RickMenza ,

I whipped up a quick example. A couple of notes:

1) GUIX only supports creating ALPHAMAP gradients today, which means it generates an 8bpp alphamap and you can then runtime assign the color used to draw the alphamap by initializing your brush. That's probably what you want anyway (that's what everybody wants!) but just to make sure you understand what's happening.

2) I purposely made it so the code calls "CreateGradient" every time you push the button, even though it really doesn't need to because the same gradient is being used every time, just drawn in different brush colors. I just wanted to demonstrate that gx_utility_gradient_create always check to see if the requested gradient has already been created, and if so it returns the existing gradient alphamap instead of creating a brand new one. If you were to check on the amount of the scratchpad memory that is free, it should only decrease on the first call and then stay constant.

There is a VisualStudio 2019 project included that should allow you to build and run as a desktop app. Let me know if you have any issues.

Best Regards

[guix_gradient_test.zip](https://github.com/azure-rtos/guix/files/6611686/guix_gradient_test.zip)

**Comment by RickMenza** [comment]
Hi Ken,

Thank you very much. Your example help me to understand the gradient functionality and I am now able to do what I want in my application.

Have a nice day!
Regards,
Richard


De : Ken Maxwell ***@***.***>
Envoyé : 7 juin 2021 16:03
À : azure-rtos/guix ***@***.***>
Cc : Richard Jobin ***@***.***>; Mention ***@***.***>
Objet : Re: [azure-rtos/guix] How drawing gradient color (#21)


Hello @RickMenza<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRickMenza&data=04%7C01%7C%7C73665605208b4846bf0308d929ef3991%7Cf193f6f562be492d897d776cde125585%7C1%7C0%7C637586932163729345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WMwAkzF2OrTmI5x9aBd8WY5w6w52k5A7yJJFwgKalQY%3D&reserved=0> ,

I whipped up a quick example. A couple of notes:

  1.  GUIX only supports creating ALPHAMAP gradients today, which means it generates an 8bpp alphamap and you can then runtime assign the color used to draw the alphamap by initializing your brush. That's probably what you want anyway (that's what everybody wants!) but just to make sure you understand what's happening.
  2.  I purposely made it so the code calls "CreateGradient" every time you push the button, even though it really doesn't need to because the same gradient is being used every time, just drawn in different brush colors. I just wanted to demonstrate that gx_utility_gradient_create always check to see if the requested gradient has already been created, and if so it returns the existing gradient alphamap instead of creating a brand new one. If you were to check on the amount of the scratchpad memory that is free, it should only decrease on the first call and then stay constant.

There is a VisualStudio 2019 project included that should allow you to build and run as a desktop app. Let me know if you have any issues.

Best Regards

guix_gradient_test.zip<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fazure-rtos%2Fguix%2Ffiles%2F6611686%2Fguix_gradient_test.zip&data=04%7C01%7C%7C73665605208b4846bf0308d929ef3991%7Cf193f6f562be492d897d776cde125585%7C1%7C0%7C637586932163739339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UKCAYU1w5CXZn%2FienTX%2FPsVLWxik4OcGz2sp0aZZzN0%3D&reserved=0>

-
